v {xschem version=3.4.8RC file_version=1.2}
G {}
K {}
V {}
S {}
F {}
E {}
N -560 -160 -540 -160 {
lab=RST_Z}
N -560 -140 -540 -140 {
lab=START}
N -240 -140 -220 -140 {
lab=CLK_DATA}
N -240 -160 -220 -160 {
lab=DATA[5:0]}
N -560 -120 -540 -120 {
lab=EN_OFFSET_CAL}
N -560 180 -540 180 {
lab=CLK}
N -560 -100 -540 -100 {
lab=SINGLE_ENDED}
C {devices/lab_pin.sym} -540 -60 0 0 {name=p177 sig_type=std_logic lab=COMP_P}
C {devices/lab_pin.sym} -240 -40 0 1 {name=p181 sig_type=std_logic lab=EN_VCM[10:0]}
C {devices/lab_pin.sym} -240 180 0 1 {name=p189 sig_type=std_logic lab=EN_COMP}
C {devices/lab_pin.sym} -240 -80 0 1 {name=p191 sig_type=std_logic lab=SMPL}
C {devices/lab_pin.sym} -540 0 0 0 {name=p231 sig_type=std_logic lab=SMPL_ON_P}
C {devices/lab_pin.sym} -540 20 0 0 {name=p256 sig_type=std_logic lab=SMPL_ON_N}
C {devices/lab_wire.sym} -390 360 2 0 {name=p76 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -390 -190 0 1 {name=p171 sig_type=std_logic lab=VDD}
C {devices/ipin.sym} -560 -160 0 0 {name=p172 lab=RST_Z}
C {devices/ipin.sym} -560 -140 0 0 {name=p173 lab=START}
C {devices/opin.sym} -220 -140 0 0 {name=p174 lab=CLK_DATA}
C {devices/lab_pin.sym} -240 220 0 1 {name=p201 sig_type=std_logic lab=OFFSET_CAL_CYCLE}
C {devices/lab_pin.sym} -240 240 0 1 {name=p219 sig_type=std_logic lab=EN_VOS_CAL}
C {devices/opin.sym} -220 -160 0 0 {name=p4 lab=DATA[5:0]}
C {devices/lab_pin.sym} -240 0 0 1 {name=p132 sig_type=std_logic lab=EN_VCM_SW}
C {devices/lab_pin.sym} -240 -20 0 1 {name=p131 sig_type=std_logic lab=EN_VCM_DUMMY}
C {devices/lab_pin.sym} -240 100 0 1 {name=p134 lab=EN_VSS_N[10:0]}
C {devices/lab_pin.sym} -240 80 0 1 {name=p135 lab=EN_REF_Z_N[10:0]}
C {devices/ipin.sym} -560 -120 0 0 {name=p11 lab=EN_OFFSET_CAL}
C {devices/ipin.sym} -560 180 0 0 {name=p15 lab=CLK}
C {devices/lab_pin.sym} -540 240 0 0 {name=p23 sig_type=std_logic lab=EN_VCM_SW}
C {devices/lab_pin.sym} -540 260 0 0 {name=p24 sig_type=std_logic lab=EN_VCM[10:0]}
C {devices/lab_pin.sym} -240 60 0 1 {name=p31 lab=EN_VSS_P_BBM[10:0]}
C {devices/lab_pin.sym} -240 40 0 1 {name=p32 lab=EN_REF_Z_P_BBM[10:0]}
C {devices/ipin.sym} -560 -100 0 0 {name=p9 lab=SINGLE_ENDED}
C {devices/code_shown.sym} 140 -40 0 0 {name=s2 only_toplevel=false value="VDD VDD 0 1.8
VSS VSS 0 0

* Clock hệ thống: 20 MHz
VCLK CLK 0 PULSE(0 1.8 0 0.1n 0.1n 25n 50n)

* Reset active-low
VRST RST_Z 0 PWL(0 0 100n 0 100.1n 1.8)

* START: 1 xung sau reset
VSTART START 0 PWL(0 0 120n 0 120.1n 1.8 170n 1.8 170.1n 0)

* Các chế độ
VENOFF EN_OFFSET_CAL 0 0
VSINGLE SINGLE_ENDED 0 0

* Đầu vào COMP_P bằng sóng sin
VSIN COMP_P 0 SIN(0.9 0.9 50Meg 0 0)

* Các input chưa dùng = 0
VZ1 SMPL_ON_P 0 0
VZ2 SMPL_ON_N 0 0
VZ3 EN_VCM_SW 0 0
VZ4 EN_VOS_CAL 0 0
VZ5 OFFSET_CAL_CYCLE 0 0



.tran 0.2n 2u
.probe v(CLK) v(COMP_P) v(DATA0) v(DATA1) v(DATA2) v(CLK_DATA)
.end"}
C {state_machine/state_machine.sym} -760 90 0 0 {}
C {devices/code_shown.sym} -440 550 0 0 {name=MODELS only_toplevel=true
format="tcleval( @value )"
value="
.include $::180MCU_MODELS/design.ngspice
.lib $::180MCU_MODELS/sm141064.ngspice typical
.lib $::180MCU_MODELS/sm141064.ngspice cap_mim
.lib $::180MCU_MODELS/sm141064.ngspice res_typical
.lib $::180MCU_MODELS/sm141064.ngspice moscap_typical
.lib $::180MCU_MODELS/sm141064.ngspice mimcap_typical
.lib $::180MCU_MODELS/sm141064.ngspice res_statistical
.lib $::180MCU_MODELS/smbb000149.ngspice typical

"}
C {devices/code_shown.sym} -450 810 0 0 {name=s3 only_toplevel=false value="

* Models for standard digital cells

.include $PDK_ROOT/gf180mcuD/libs.ref/gf180mcu_fd_sc_mcu7t5v0/spice/gf180mcu_fd_sc_mcu7t5v0.spice


* Spice netlist for state machine generated by openlane
.include [xschem get current_dirname]/state_machine/openlane/runs/gf_run5/results/signoff/state_machine.spice


"
name=MODELS only_toplevel=true
format="tcleval( @value )"
value="
.include $::180MCU_MODELS/design.ngspice
.lib $::180MCU_MODELS/sm141064.ngspice typical
.lib $::180MCU_MODELS/sm141064.ngspice cap_mim
.lib $::180MCU_MODELS/sm141064.ngspice res_typical
.lib $::180MCU_MODELS/sm141064.ngspice moscap_typical
.lib $::180MCU_MODELS/sm141064.ngspice mimcap_typical
.lib $::180MCU_MODELS/sm141064.ngspice res_statistical
.lib $::180MCU_MODELS/smbb000149.ngspice typical

"}
