/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSEDSIGNAL */
/* Generated by Yosys 0.55+112 (git sha1 bf9aaac0f, x86_64-conda-linux-gnu-c++ 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-opensource-eda/conda-opensource-eda/workdir/conda-env/conda-bld/yosys_1753479840435/work=/usr/local/src/conda/yosys-0.55_113_gbf9aaac0f -fdebug-prefix-map=/home/khanhduy/conda-gf180mcu-env/envs/gf180mcu-env=/usr/local/src/conda-prefix -fPIC -O3) */

/* verilator lint_on UNUSEDSIGNAL */
/* verilator lint_on UNDRIVEN */

